##
# Fast target build-check image.
#
# This Dockerfile is intended to be invoked with a reduced build context
# (no corpus/PoCs) for quick verification after updating target releases/build
# scripts.
#
# Unlike docker/Dockerfile, it does NOT fetch/build any fuzzer. It compiles
# Magma instrumentation + the target using clang + libFuzzer runtime
# (-fsanitize=fuzzer) just to validate that the target build still works.
##

FROM ubuntu:24.04 AS magma_core

RUN apt-get update && apt-get install -y \
    sudo \
    ca-certificates \
    git \
    wget \
    clang \
    llvm

ARG magma_root=./

ENV MAGMA_R=/magma
ENV OUT=/magma_out
ENV COV=/magma_cov
ENV SHARED=/magma_shared

ENV CC=/usr/bin/clang
ENV CXX=/usr/bin/clang++
ENV LD=/usr/bin/ld
ENV AR=/usr/bin/ar
ENV AS=/usr/bin/as
ENV NM=/usr/bin/nm
ENV RANLIB=/usr/bin/ranlib

ARG USER_ID=1001
ARG GROUP_ID=1001
RUN mkdir -p /home && \
	groupadd -g ${GROUP_ID} magma && \
	useradd -l -u ${USER_ID} -K UMASK=0000 -d /home -g magma magma && \
	chown magma:magma /home
RUN	echo "magma:amgam" | chpasswd && usermod -a -G sudo magma
RUN echo "magma ALL=(ALL:ALL) NOPASSWD:ALL" >> /etc/sudoers

RUN mkdir -p ${SHARED} ${OUT} ${COV} && \
	chown magma:magma ${SHARED} ${OUT} ${COV} && \
	chmod 744 ${SHARED} ${OUT} ${COV}

ARG magma_path=magma
ENV MAGMA=${MAGMA_R}/${magma_path}
USER root:root
RUN mkdir -p ${MAGMA} && chown magma:magma ${MAGMA}
COPY --chown=magma:magma ${magma_root}/${magma_path} ${MAGMA}/
RUN ${MAGMA}/preinstall.sh
USER magma:magma
RUN ${MAGMA}/prebuild.sh

ARG target_name
ARG target_path=targets/${target_name}
ENV TARGET_NAME=${target_name}
ENV TARGET=${MAGMA_R}/${target_path}
ARG target_version
ENV TARGET_VERSION=${target_version}
USER root:root
RUN mkdir -p ${TARGET} && chown magma:magma ${TARGET}
COPY --chown=magma:magma ${magma_root}/${target_path} ${TARGET}/
RUN ${TARGET}/preinstall.sh
USER magma:magma
RUN ${MAGMA}/fetch_target.sh
RUN ${MAGMA}/apply_patches.sh

ARG isan
ARG harden
ARG canaries
ARG fixes

ARG ISAN_FLAG=${isan:+-DMAGMA_FATAL_CANARIES}
ARG HARDEN_FLAG=${harden:+-DMAGMA_HARDEN_CANARIES}
ARG CANARIES_FLAG=${canaries:+-DMAGMA_ENABLE_CANARIES}
ARG FIXES_FLAG=${fixes:+-DMAGMA_ENABLE_FIXES}
ARG BUILD_FLAGS="-include ${MAGMA}/src/canary.h ${CANARIES_FLAG} ${FIXES_FLAG} ${ISAN_FLAG} ${HARDEN_FLAG} -g -O0"

ENV CFLAGS=${BUILD_FLAGS}
ENV CXXFLAGS=${BUILD_FLAGS}
ENV LIBS="-l:magma.o -lrt"
ENV LDFLAGS="-L${OUT} -g"
ENV LIB_FUZZING_ENGINE="-fsanitize=fuzzer"

ARG source_coverage
ENV SOURCE_COVERAGE=${source_coverage:+1}
ENV SOURCE_COVERAGE_FLAGS=${source_coverage:+"-fprofile-instr-generate -fcoverage-mapping"}

# Build-check: compile Magma instrumentation + target fuzz binary/binaries.
RUN ${MAGMA}/build.sh
RUN ${TARGET}/build.sh

ENTRYPOINT ["/bin/bash", "-c", "${MAGMA}/run.sh"]
