###
# Configuration parameters for libtiff PoCs
# Variables available to use in bug commands:
# - env CRASH_INPUT: /test/crash_input (from run_pocs.sh)
# - env CRASH_OUTPUT: /test/crash_output (from run_pocs.sh)
# - env CRASH_OUTPUT_NULL: /dev/null (from run_pocs.sh)
###

##
# Which libtiff bugs to build PoCs for. default: None
##
libtiff_BUGS=(TIF007 TIF009)

##
# Commands to reproduce PoC for each specified bug
## 
TIF007_COMMAND="tiffinfo -D ${CRASH_INPUT} ${CRASH_OUTPUT}"
TIF009_COMMAND="tiffcp ${CRASH_INPUT} ${CRASH_OUTPUT}"
