###
# Configuration parameters for poppler PoCs
# Variables available to use in bug commands:
# - env CRASH_INPUT: /test/crash_input (from run_pocs.sh)
# - env CRASH_OUTPUT: /test/crash_output (from run_pocs.sh)
# - env CRASH_OUTPUT_NULL: /dev/null (from run_pocs.sh)
###

##
# Which poppler bugs to build PoCs for. default: None
##
poppler_BUGS=(PDF002 PDF010 PDF014 PDF018 PDF021)

##
# Commands to reproduce PoC for each specified bug
## 
PDF002_COMMAND="pdfimages ${CRASH_INPUT} ${CRASH_OUTPUT_NULL}"
PDF010_COMMAND="pdftoppm -mono -cropbox ${CRASH_INPUT}"
PDF014_COMMAND="pdftoppm -mono -cropbox ${CRASH_INPUT}"
PDF018_COMMAND="pdfimages ${CRASH_INPUT} ${CRASH_OUTPUT_NULL}"
PDF021_COMMAND="pdfimages ${CRASH_INPUT} ${CRASH_OUTPUT_NULL}"
